import { useEffect, useState } from "react";
import { getData, saveData } from "../data";

export default function IssueBooks() {
  const [books, setBooks] = useState([]); const [issues, setIssues] = useState([]); const [student, setStudent] = useState("Bebo Student"); const [book, setBook] = useState("");
  useEffect(() => { setBooks(getData("libraryBooks")); setIssues(getData("libraryIssues")); }, []);
  const issue = e => { e.preventDefault(); const b = books.find(x => x.id === Number(book)); if (!b || b.status !== "Available") return alert("Select an available book."); const updatedBooks = books.map(x => x.id === b.id ? { ...x, status: "Issued" } : x); const updatedIssues = [...issues, { id: Date.now(), student, book: b.title, issueDate: new Date().toISOString().slice(0,10), dueDate: new Date(Date.now()+14*86400000).toISOString().slice(0,10), status: "Issued" }]; setBooks(updatedBooks); setIssues(updatedIssues); saveData("libraryBooks", updatedBooks); saveData("libraryIssues", updatedIssues); alert("Book issued successfully."); };
  return <><div className="breadcrumb">Home <span>›</span> Issue Book</div><div className="page-title"><h1>Issue Book</h1></div><section className="panel"><form className="issue-form" onSubmit={issue}><label>Student<input value={student} onChange={e=>setStudent(e.target.value)} /></label><label>Book<select value={book} onChange={e=>setBook(e.target.value)}><option value="">Select book</option>{books.filter(b=>b.status === "Available").map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><button className="primary-btn">Issue Book</button></form></section><section className="panel"><h3>Issued Books</h3><div className="table-wrap"><table><thead><tr><th>Student</th><th>Book</th><th>Issue Date</th><th>Due Date</th><th>Status</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td>{i.student}</td><td>{i.book}</td><td>{i.issueDate}</td><td>{i.dueDate}</td><td><span className="badge danger">{i.status}</span></td></tr>)}</tbody></table></div></section></>;
}
